on: [pull_request,workflow_dispatch] 
 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: bhuvi11/Test_action@v3
      with:
        who-to-greet: 'Testing for bhuvi repository action'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
    - run: echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
    - run: echo ${{(github.event.pull_request.number)}}
    
      shell: bash
    - run: echo hello world > math-homework.txt
    - name: test
      run : |
       echo "::set-output name=action_fruit::${{github.workspace}}/math-homework.txt" 
       docker images
       docker pull securetest1/sest
       docker run securetest1/sest .
      id: run_test
    - name: get test
      run: echo ${{(steps.run_test.outputs.action_fruit)}}
    
    - uses: actions/upload-artifact@v2
      with: 
         name: homework
         path: math-homework.txt

       
    - uses: actions/download-artifact@v2
      with:
       name: homework
    - run: zip -r homework.zip math-homework.txt 
    - run: ls ${{github.workspace}}

  Test:
    needs: hello_world_job
    runs-on: ubuntu-latest
    name: A job to say hello 1
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: bhuvi11/Test_action@v3
      with:
        who-to-greet: 'Testing for bhuvi repository action'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
    - run: echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
    - run: echo ${{(github.event.pull_request.number)}}
    
       
     
  
